version: "3"

services:
  worker:
      build: .
      volumes:
        - ./:/code
      environment:
        - WORKER_HOST=worker
        - WORKER_PORT=5690
      expose:
        - "5690"
        - "5691"
      command: sleep 365d

  publisher:
      build: .
      volumes:
        - ./:/code
      environment:
        - WORKER_HOST=worker
        - WORKER_PORT=5690
      ports:
        - "5690:5690"
        - "5691:5691"
      expose:
        - "5690"
        - "5691"
      command: sleep 365d
      links:
        - worker